services:
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: .
    env_file:
      - .env
    command: gunicorn star_burger.wsgi:application --bind 127.0.0.1:8000
    volumes:
      - media_data:/app/media
    restart: always
    depends_on:
      - db

volumes:
  postgres_data:
  media_data: