# Generated by Django 5.2.1 on 2025-05-10 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20250509_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='фиксированная цена'),
        ),
    ]
