# Generated by Django 5.2.1 on 2025-05-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Необработанный'), ('processing', 'В обработке'), ('preparing', 'Готовится'), ('delivering', 'Доставляется'), ('completed', 'Завершен')], db_index=True, max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
