# Generated by Django 5.2.1 on 2025-05-12 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_payment_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, unique=True, verbose_name='адрес')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='долгота')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='широта')),
                ('geocode_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата последнего запроса к geocoder')),
            ],
            options={
                'verbose_name': 'локация',
                'verbose_name_plural': 'локации',
            },
        ),
    ]
