# Generated by Django 5.2.1 on 2025-05-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_coordinate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinate',
        ),
    ]
