# Generated by Django 5.2.1 on 2025-05-15 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_alter_order_address_alter_order_firstname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Элементы заказа', 'verbose_name_plural': 'Элементы заказов'},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
    ]
